In [1]:
import torch
import numpy as np

In [7]:
numpy_array= np.array([1,2,3])
torch_tensor1 = torch.from_numpy(numpy_array)
torch_tensor2 = torch.Tensor(numpy_array)
torch_tensor3 = torch.tensor(numpy_array)

In [8]:
torch_tensor1

tensor([1, 2, 3])

In [9]:
torch_tensor2

tensor([1., 2., 3.])

In [12]:
torch_tensor3

tensor([1, 2, 3])

In [13]:
a = [1,2,3]
torch_tensor1 = torch.tensor(a)
a1 = (1,2,3)
torch_tensor2  = torch.tensor(a1)